# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f3e48e3746618680d7a3164b796e1c8bd3ab2c1b64d2c791f463d43f4058580c6e5d877ef8412707bfe48ef09885a3ba5d346fc310220ec795e6ed5da5fcb57

test:
  secret_key_base: c8960009af1caa4990f87cc674cd80818bfa565e7c27728b8c2acf5f6ec98457a9725464d270fdb205c0f40e78100a831aab31ef450e3b0bd7d2c6a73ee3cb06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
